### ISSUE TITLE
[iOS] Data decoding for Incoming WalletConnect transactions

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1710] opened 2021-12-16 17:30 UTC
We need to implement data decoding for incoming WC transactions.

**Current WEB design**
![Screenshot 2022-03-29 at 21.09.40.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/5d5cebac-7816-4ceb-8ac1-f012f43f0033)

The known address feature will be implemented as part of v2 of the CGS response.

[Backend issue](https://github.com/gnosis/safe-client-gateway/issues/840)

**Comment by DmitryBespalov** [comment] 2022-03-29 12:24
I don't think we will have this in the foreseeable future, and this is won't fix.

**Comment by sche** [comment] 2022-03-29 14:06
@DmitryBespalov I will adjust it for decoding data. Relevant [conversation here](https://gnosisinc.slack.com/archives/CQB729LLF/p1648559663170409)

**Comment by DmitryBespalov** [comment] 2022-07-06 11:54
Duplicate of #2415

**Closed as completed by DmitryBespalov** 2022-07-06 11:54 UTC
Labels: enhancement, Backend missing
