### ISSUE TITLE
Japanese keyboard strange behavior 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#521] opened 2020-08-28 13:43 UTC
When write safe name in Japanese the keyboard act strangely, 

When you enter some text then dismiss the keyboard, then go back to the textfield the text removed, 
When you type something then use the autocomplete the textfield become empty.

**Comment by tschubotz** [comment] 2020-09-16 09:30
Who uses a Japanese keyboard? 🙈

Just assigned `minor` since whatever the issue is, it might happen to other non English keyboards too. 
Still, let's timebox this since we currently only optimize our app for English.

**Comment by DmitryBespalov** [comment] 2020-10-13 13:09
Needs QA on English keyboards

**Comment by tschubotz** [comment] 2020-10-16 12:08
@liliya-soroka could you please check if this issue exists for English keyboards as well?

If not, could you please close this issue? :)

**Comment by liliya-soroka** [comment] 2020-10-20 13:43
The issue is not reproducable for the English keyboard 
The issue is closed
app version 2.4.0 - 168

**Closed as completed by liliya-soroka** 2020-10-20 13:43 UTC
Labels: bug, Minor
