### ISSUE TITLE
[iOS] Cancelled state is displayed for a successful transaction

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-ios#480] opened 2020-08-18 08:44 UTC
**Bug description**
From [discord](https://discordapp.com/channels/477106835862716416/477391201708802058/744930787555672144):
> Quick bug report: using Gnosis Safe Multi-sig Rinkeby web app and a 2 out of 3 multisig, I created a transaction request and signed using 2 of the 3 consigners.  Transaction was successfully sent, and was shown as being successfully sent from the webUI, but when looking at the same transaction using Gnosis Safe Multi-sig mobile (iOS version 0.7.0) it was marked as 'Outgoing transfer   Cancelled' for a few minutes before updating to display the correct state 'Outgoing transfer   Success'.  Could have been confusing for a user to see 'Outgoing transfer   Cancelled' in the mobile app right after approving the transaction. 

**Expected Result**
Web and iOS app display the same state or at least not cancelled

**Device & App version**
 - App version: 0.7.0

**Comment by DmitryBespalov** [comment] 2020-08-24 10:20
We're aware of it, this needs to wait after public release when we'll integrate the safe client gateway

**Comment by tschubotz** [comment] 2020-08-28 12:12
assigning minor since this has to wait until after the public release as to Dima's comment.

**Comment by liliya-soroka** [comment] 2020-08-28 17:47
We had an issue for it , but I can not find. Probably it was moved to the back-end board
Found - client-gateway issue https://github.com/gnosis/safe-client-gateway/issues/37

**Comment by DmitryBespalov** [comment] 2020-10-13 13:07
is this ever going to be fixed? @jpalvarezl @rmeissner

**Comment by rmeissner** [comment] 2020-10-13 13:15
As stated above it is related to https://github.com/gnosis/safe-client-gateway/issues/37 and the issue is in "Not Now" so this will not be fixed in upcoming sprints, but with the current cache invalidation setup this should only be for a couple seconds (< 1 min).

**Comment by liliya-soroka** [comment] 2021-03-25 14:52
not an issue after a new view of txs list was implemented.

**Closed as completed by liliya-soroka** 2021-03-25 14:52 UTC
Labels: bug, Minor
