### ISSUE TITLE
[Intercom] Push Notifications

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1657] opened 2021-12-07 08:37 UTC
Implement push notifications for incoming Intercom messages when the App is closed or in the background.

- [x] Display incoming messages
- [x] Opening the push message should open App and show Intercom chat screen in a popover

**Comment by biafra23** [comment] 2021-12-07 14:10
Regarding: Display incoming message:
- According to @TanyaEfremova we should show it only on certain screens. For example not when the user is in the process of signing (or in the future creating a transfer)

In that case we should increase the badge on the `Chat with us` setting.

This should be the same for any incoming message. Regardless of push or while the app is already open.

**Comment by biafra23** [comment] 2021-12-07 14:42
@TanyaEfremova said: No number in the badge necessary. Just a small coloured badge.

**Comment by TanyaEfremova** [comment] 2021-12-07 15:36
Screens where we could show the incoming message:
- Balances;
- Transactions: queue, history;
- Settings: app, safe
- Dapps (if possible, because it conflicts with walletConnect btn)
 
Such screens as tx details should not show the message, as it might conflict with the action buttons (Confirm, Execute).

**Comment by liliya-soroka** [comment] 2022-01-03 14:10
Reopened: Click on push notification opens app but doesn't open intercom chat. Also nothing happens on "Chat with us" click. So as a user I know that I got a new message from support but I can not check it. The app restart is required to open intercom chat 

Steps:
1. Send app to the background or close it
2. send incoming notification from intercom to the user in the app
3. click notification
Current result: the app is opened but the intercom chat doesn't appear. 
If you go to the settings and click "chat with us" nothing happens
https://drive.google.com/file/d/1985rStTNKEwGUoZc8zGBVPVFZ2tX7kxP/view?usp=sharing
app version 3.6.0 (769)
staging

**Comment by liliya-soroka** [comment] 2022-01-13 14:24
Reopened with additional step:
The app should be locked with passcodes when the push notification is clicked.
After app unlock the intercome message is not displayed 
If the user opens the app from push notification before it's locked with passcode everything works

app version 3.6.0 (798)

**Comment by biafra23** [comment] 2022-01-17 09:14
I cannot reproduce the error, @liliya-soroka describes. But I have another one that involves opening from Push notification and having a passcode set: 

(Needs better description)
And after a while the screen is unlocked automatically when I recall the application. But the chat is always shown.
And then, when I close the chat the screen is locked. So that is a bug.

**Closed as completed** 2022-01-19 16:31 UTC
Labels: bug, enhancement, Critical
