### ISSUE TITLE
[iOS] No notifications on L2 networks if no added owners

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1581] opened 2021-11-11 15:00 UTC
**Bug description**
No notifications on L2 networks if no added owners

**Steps To Reproduce**
1. add safe on L2 network but don't add any owner key ( any key)
2. send incoming or outgoing tx for the added safe

Current result: No incoming or outgoing tx notification

**Expected Result** Incoming and outgoing Notifications should be received without added keys on L2 networks ( works on android)

**Device & App version**
 - Device/OS: [iphone X/14.8
 - App version: 3.3.0 (676)
 
**Environment**
prod , xDai, polygon, bsc
**Additional info**
(Optional)

**Comment by sche** [comment] 2021-11-11 15:49
> Expected Result Incoming and outgoing Notifications should be received without added keys on L2 networks ( works on android)

@liliya-soroka is it about push notifications? If yes, then this might be an issue with Android (it could be registered before, but then failed to unregister)

**Comment by DmitryBespalov** [comment] 2021-11-15 12:40
@andrey the issue is that iOS doesn't receive any notifications on L2 chains, however Android app does

**Comment by DmitryBespalov** [comment] 2021-12-07 16:04
probably should be fixed by another bug fix, I need to check it.

**Comment by sche** [comment] 2021-12-13 14:02
@liliya-soroka could you please check it on the latest RC?

**Comment by liliya-soroka** [comment] 2021-12-15 14:26
hm, can not reproduce in 3.5.0 (743)

**Closed as completed** 2022-01-03 08:40 UTC
Labels: bug, Major
