### ISSUE TITLE
[iOS][WC]Snackbar message is not seen fully if the popup window was opened

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2133] opened 2022-03-28 16:19 UTC
**Bug description**
Snackbar message is not seen fully

ios: 14.8 os
iPhone 11

**Steps To Reproduce**
1. go to the tx details
2. try to sign tx using MM key
3. cancel the signing in MM
Current result: The error message is displaced because of the pop-up window 
**Expected Result**
The message should be seen fully, mobe it a little bit down
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8a6c3707-a924-4cb5-b94e-8801fc25eb76)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.9.0 (979)

Relates to 
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/2077
 
**Environment**
staging 
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment] 2022-03-29 09:40
@liliya-soroka I can't reproduce this neither on simulator or a device. Is it still happens on the latest build?

**Comment by DmitryBespalov** [comment] 2022-03-29 12:21
won't fix because doesn't happen on iOS 15

**Closed as completed by DmitryBespalov** 2022-03-29 12:21 UTC
Labels: bug, wontfix, Minor
